import { Suspense } from "react"
import Logo from "./components/Logo"
import Navigation from "./components/Navigation"
import Loading from "./loading"

export const metadata = {
  title: "Ross Oasis",
  description: "Generated by Next.js",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <Logo />
        </header>
        <Navigation />

        <main>
          <Suspense fallback={<Loading />}>{children}</Suspense>
        </main>
        <footer>Copyright by Ross Oasis </footer>
      </body>
    </html>
  )
}
